### ISSUE TITLE
关于对比实验对象Sortledton的问题

### ISSUE THREAD

**Issue by Anna521** [Stardust-SJF/Spruce#1]
请问您在做对比实验，使用 gfe_driver 配置 Sortledton 时，是否出现下面这些错误，如果出现了，又是怎样解决的呢？
In file included from /home/anna/gfe_driver_for_sortledton/gfe_driver/sortledton/algorithms/GAPBSAlgorithms.h:8,
                 from ../library/sortledton/sortledton_driver.cpp:24:
/home/anna/gfe_driver_for_sortledton/gfe_driver/sortledton/third-party/gapbs.h:52:3: error: redefinition of ‘template<class T, class U> T gapbs::fetch_and_add(T&, U)’
   52 | T fetch_and_add(T &x, U inc) {
      |   ^~~~~~~~~~~~~
In file included from ../library/sortledton/sortledton_driver.cpp:11:
../third-party/gapbs/gapbs.hpp:52:3: note: ‘template<class T, class U> T gapbs::fetch_and_add(T&, U)’ previously declared here
   52 | T fetch_and_add(T &x, U inc) {
      |   ^~~~~~~~~~~~~
In file included from /home/anna/gfe_driver_for_sortledton/gfe_driver/sortledton/algorithms/GAPBSAlgorithms.h:8,
                 from ../library/sortledton/sortledton_driver.cpp:24:
/home/anna/gfe_driver_for_sortledton/gfe_driver/sortledton/third-party/gapbs.h:57:6: error: redefinition of ‘template<class T> bool gapbs::compare_and_swap(T&, const T&, const T&)’
   57 | bool compare_and_swap(T &x, const T &old_val, const T &new_val) {
      |      ^~~~~~~~~~~~~~~~
In file included from ../library/sortledton/sortledton_driver.cpp:11:
../third-party/gapbs/gapbs.hpp:57:6: note: ‘template<class T> bool gapbs::compare_and_swap(T&, const T&, const T&)’ previously declared here
   57 | bool compare_and_swap(T &x, const T &old_val, const T &new_val) {
      |      ^~~~~~~~~~~~~~~~
In file included from /home/anna/gfe_driver_for_sortledton/gfe_driver/sortledton/algorithms/GAPBSAlgorithms.h:8,
                 from ../library/sortledton/sortledton_driver.cpp:24:
/home/anna/gfe_driver_for_sortledton/gfe_driver/sortledton/third-party/gapbs.h:62:13: error: redefinition of ‘bool gapbs::compare_and_swap(T&, const T&, const T&) [with T = float]’
   62 | inline bool compare_and_swap(float &x, const float &old_val, const float &new_val) {
      |             ^~~~~~~~~~~~~~~~
In file included from ../library/sortledton/sortledton_driver.cpp:11:
../third-party/gapbs/gapbs.hpp:62:13: note: ‘bool gapbs::compare_and_swap(T&, const T&, const T&) [with T = float]’ previously declared here
   62 | inline bool compare_and_swap(float &x, const float &old_val, const float &new_val) {
      |             ^~~~~~~~~~~~~~~~
In file included from /home/anna/gfe_driver_for_sortledton/gfe_driver/sortledton/algorithms/GAPBSAlgorithms.h:8,
                 from ../library/sortledton/sortledton_driver.cpp:24:
/home/anna/gfe_driver_for_sortledton/gfe_driver/sortledton/third-party/gapbs.h:69:13: error: redefinition of ‘bool gapbs::compare_and_swap(T&, const T&, const T&) [with T = double]’
   69 | inline bool compare_and_swap(double &x, const double &old_val, const double &new_val) {
      |             ^~~~~~~~~~~~~~~~
In file included from ../library/sortledton/sortledton_driver.cpp:11:
../third-party/gapbs/gapbs.hpp:69:13: note: ‘bool gapbs::compare_and_swap(T&, const T&, const T&) [with T = double]’ previously declared here
   69 | inline bool compare_and_swap(double &x, const double &old_val, const double &new_val) {
      |             ^~~~~~~~~~~~~~~~
In file included from /home/anna/gfe_driver_for_sortledton/gfe_driver/sortledton/algorithms/GAPBSAlgorithms.h:8,
                 from ../library/sortledton/sortledton_driver.cpp:24:
/home/anna/gfe_driver_for_sortledton/gfe_driver/sortledton/third-party/gapbs.h:164:7: error: redefinition of ‘class gapbs::Bitmap’
  164 | class Bitmap {
      |       ^~~~~~
In file included from ../library/sortledton/sortledton_driver.cpp:11:
../third-party/gapbs/gapbs.hpp:164:7: note: previous definition of ‘class gapbs::Bitmap’
  164 | class Bitmap {
      |       ^~~~~~
In file included from /home/anna/gfe_driver_for_sortledton/gfe_driver/sortledton/algorithms/GAPBSAlgorithms.h:8,
                 from ../library/sortledton/sortledton_driver.cpp:24:
/home/anna/gfe_driver_for_sortledton/gfe_driver/sortledton/third-party/gapbs.h:223:7: error: redefinition of ‘class gapbs::SlidingQueue<T>’
  223 | class SlidingQueue {
      |       ^~~~~~~~~~~~
In file included from ../library/sortledton/sortledton_driver.cpp:11:
../third-party/gapbs/gapbs.hpp:223:7: note: previous definition of ‘class gapbs::SlidingQueue<T>’
  223 | class SlidingQueue {
      |       ^~~~~~~~~~~~
In file included from /home/anna/gfe_driver_for_sortledton/gfe_driver/sortledton/algorithms/GAPBSAlgorithms.h:8,
                 from ../library/sortledton/sortledton_driver.cpp:24:
/home/anna/gfe_driver_for_sortledton/gfe_driver/sortledton/third-party/gapbs.h:275:7: error: redefinition of ‘class gapbs::QueueBuffer<T>’
  275 | class QueueBuffer {
      |       ^~~~~~~~~~~
In file included from ../library/sortledton/sortledton_driver.cpp:11:
../third-party/gapbs/gapbs.hpp:275:7: note: previous definition of ‘class gapbs::QueueBuffer<T>’
  275 | class QueueBuffer {
      |       ^~~~~~~~~~~
In file included from /home/anna/gfe_driver_for_sortledton/gfe_driver/sortledton/algorithms/GAPBSAlgorithms.h:8,
                 from ../library/sortledton/sortledton_driver.cpp:24:
/home/anna/gfe_driver_for_sortledton/gfe_driver/sortledton/third-party/gapbs.h:318:7: error: redefinition of ‘class gapbs::pvector<T_>’
  318 | class pvector {
      |       ^~~~~~~
In file included from ../library/sortledton/sortledton_driver.cpp:11:
../third-party/gapbs/gapbs.hpp:318:7: note: previous definition of ‘class gapbs::pvector<T_>’
  318 | class pvector {

**Comment by Stardust-SJF** [comment]
你好，我印象中有遇到过这样的问题，可能需要检查文件是否被多次include，添加防止文件被多次包含的宏

**Comment by Anna521** [comment]
> 你好，我印象中有遇到过这样的问题，可能需要检查文件是否被多次include，添加防止文件被多次包含的宏

请问有数据预处理步骤吗？怎么将从 Stanford 数据集转换为 Sortledton等论文中所需的 .prperties ， .v ， .e等文件

**Comment by Stardust-SJF** [comment]
> > 你好，我印象中有遇到过这样的问题，可能需要检查文件是否被多次include，添加防止文件被多次包含的宏
> 
> 请问有数据预处理步骤吗？怎么将从 Stanford 数据集转换为 Sortledton等论文中所需的 .prperties ， .v ， .e等文件

已经上传了预处理相关代码以供参考。

**Comment by Anna521** [comment]
> > > 你好，我印象中有遇到过这样的问题，可能需要检查文件是否被多次include，添加防止文件被多次包含的宏
> > 
> > 
> > 请问有数据预处理步骤吗？怎么将从 Stanford 数据集转换为 Sortledton等论文中所需的 .prperties ， .v ， .e等文件
> 
> 已经上传了预处理相关代码以供参考。

非常感谢！请问你的研究方向也是图存储吗？我是电子科技大学的研究生，方便的话请问能否加个联系方式进行一些讨论交流呢？

**Comment by Stardust-SJF** [comment]
> > > > 你好，我印象中有遇到过这样的问题，可能需要检查文件是否被多次include，添加防止文件被多次包含的宏
> > > 
> > > 
> > > 请问有数据预处理步骤吗？怎么将从 Stanford 数据集转换为 Sortledton等论文中所需的 .prperties ， .v ， .e等文件
> > 
> > 
> > 已经上传了预处理相关代码以供参考。
> 
> 非常感谢！请问你的研究方向也是图存储吗？我是电子科技大学的研究生，方便的话请问能否加个联系方式进行一些讨论交流呢？

你好，目前是的，可以通过邮箱进行联系～

**Comment by Anna521** [comment]
请问为什么Concurrent Performance部分的实验不和 Sortledton 作对比呢？&nbsp;


青衫依故
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月9日(星期四) 晚上7:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Stardust-SJF/Spruce] 关于对比实验对象Sortledton的问题 (Issue #1)














     
你好，我印象中有遇到过这样的问题，可能需要检查文件是否被多次include，添加防止文件被多次包含的宏
  
请问有数据预处理步骤吗？怎么将从 Stanford 数据集转换为 Sortledton等论文中所需的 .prperties ， .v ， .e等文件
  
已经上传了预处理相关代码以供参考。
  
非常感谢！请问你的研究方向也是图存储吗？我是电子科技大学的研究生，方便的话请问能否加个联系方式进行一些讨论交流呢？
  
你好，可以通过邮箱进行联系～

**Comment by Stardust-SJF** [comment]
> 请问为什么Concurrent Performance部分的实验不和 Sortledton 作对比呢？&nbsp; 青衫依故 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年5月9日(星期四) 晚上7:54 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Stardust-SJF/Spruce] 关于对比实验对象Sortledton的问题 (Issue #1) 你好，我印象中有遇到过这样的问题，可能需要检查文件是否被多次include，添加防止文件被多次包含的宏 请问有数据预处理步骤吗？怎么将从 Stanford 数据集转换为 Sortledton等论文中所需的 .prperties ， .v ， .e等文件 已经上传了预处理相关代码以供参考。 非常感谢！请问你的研究方向也是图存储吗？我是电子科技大学的研究生，方便的话请问能否加个联系方式进行一些讨论交流呢？ 你好，可以通过邮箱进行联系～ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你好，我们在使用Sortledton开源的代码编译后进行该项测试时遇到了Segment Fault错误，因此无法得到实验结果。（另外，可以通过论文中的邮件地址进行联系）
